### ISSUE TITLE
The instructions for running the example seem to be incorrect

### ISSUE THREAD

**Issue by dane-king** [Srdjan/resto#7]
Following along the instructions to run the example are incorrect
The src files need to be copied to a lib directory in the example. This could be done either as a separate npm task, or maybe create a package.json for the example directory

I would be more than happy to help

**Comment by srdjan** [comment]
thank you for reporting this..
if you don't mind sending it, I'll be happy to take your PR 😄

**Comment by dane-king** [comment]
Sure, it might be a few days.

I ran across the issue because I was looking for a good proper rest
example, thanks for putting it out there.

Dane

**Comment by srdjan** [comment]
@dane-king FYi 
 I ended up restructuring into two repos:
- https://github.com/Srdjan/restro (now published as NPM module)
- https://github.com/Srdjan/restro.examples 
- there was a 'resto' npm module - so a slight name change and new repo was required, 'resto' is now depricated

Big change, but should make it easier in the future
Docs can still be better :)
